"""add vacancy internship resume tables

Revision ID: 670a877a4c00
Revises: cc58077f5d8d
Create Date: 2025-10-19 02:55:31.837764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670a877a4c00'
down_revision: Union[str, Sequence[str], None] = 'cc58077f5d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('status', sa.Enum('pending', 'rejected', 'closed', 'opened', 'approved', name='resumestatus'), nullable=False),
    sa.Column('name', sa.String(length=1500), nullable=True),
    sa.Column('phone', sa.String(length=1500), nullable=True),
    sa.Column('resume_link', sa.String(length=1500), nullable=True),
    sa.Column('email', sa.String(length=1500), nullable=True),
    sa.Column('confidencial', sa.Boolean(), nullable=True),
    sa.Column('mallings', sa.Boolean(), nullable=True),
    sa.Column('sms_ad', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1500), nullable=True),
    sa.Column('logo', sa.String(length=1500), nullable=True),
    sa.Column('company_name', sa.String(length=1500), nullable=True),
    sa.Column('platform', sa.Enum('alabushevo', 'pechatniki', 'rudnevo', 'micron', 'angstrem', 'miet', name='enumplatform'), nullable=False),
    sa.Column('speciality', sa.Enum('hr', 'it', 'administrative_job', 'logistic', 'marketing', 'medecine', 'microelectronic', 'sales', 'production', 'finance', 'law', name='enumspeciality'), nullable=False),
    sa.Column('responsibilities', sa.String(length=1500), nullable=True),
    sa.Column('requirements', sa.String(length=1500), nullable=True),
    sa.Column('official_employment', sa.String(length=1500), nullable=True),
    sa.Column('work_shedule', sa.String(length=1500), nullable=True),
    sa.Column('work_place', sa.String(length=1500), nullable=True),
    sa.Column('map_place', sa.String(length=1500), nullable=True),
    sa.Column('probation', sa.String(length=1500), nullable=True),
    sa.Column('salary', sa.String(length=1500), nullable=True),
    sa.Column('extra', sa.String(length=1500), nullable=True),
    sa.Column('text_promo', sa.String(length=1500), nullable=True),
    sa.Column('web_link', sa.String(length=1500), nullable=True),
    sa.Column('promo_link', sa.String(length=1500), nullable=True),
    sa.Column('confidencial', sa.Boolean(), nullable=True),
    sa.Column('mailings', sa.Boolean(), nullable=True),
    sa.Column('sms_ad', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancies',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=1500), nullable=True),
    sa.Column('logo', sa.String(length=1500), nullable=True),
    sa.Column('company_name', sa.String(length=1500), nullable=True),
    sa.Column('platform', sa.Enum('alabushevo', 'pechatniki', 'rudnevo', 'micron', 'angstrem', 'miet', name='enumplatform'), nullable=False),
    sa.Column('speciality', sa.Enum('hr', 'it', 'administrative_job', 'logistic', 'marketing', 'medecine', 'microelectronic', 'sales', 'production', 'finance', 'law', name='enumspeciality'), nullable=False),
    sa.Column('responsibilities', sa.String(length=1500), nullable=True),
    sa.Column('requirements', sa.String(length=1500), nullable=True),
    sa.Column('official_employment', sa.String(length=1500), nullable=True),
    sa.Column('work_shedule', sa.String(length=1500), nullable=True),
    sa.Column('work_place', sa.String(length=1500), nullable=True),
    sa.Column('map_place', sa.String(length=1500), nullable=True),
    sa.Column('probation', sa.String(length=1500), nullable=True),
    sa.Column('salary', sa.String(length=1500), nullable=True),
    sa.Column('extra', sa.String(length=1500), nullable=True),
    sa.Column('text_promo', sa.String(length=1500), nullable=True),
    sa.Column('web_link', sa.String(length=1500), nullable=True),
    sa.Column('promo_link', sa.String(length=1500), nullable=True),
    sa.Column('confidencial', sa.Boolean(), nullable=True),
    sa.Column('mailings', sa.Boolean(), nullable=True),
    sa.Column('sms_ad', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies')
    op.drop_table('internships')
    op.drop_table('resumes')
    # ### end Alembic commands ###
