"""add info for companies and universities

Revision ID: c90f1d15c265
Revises: 15e9448a06fe
Create Date: 2025-10-18 11:35:31.292183

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c90f1d15c265"
down_revision: Union[str, Sequence[str], None] = "15e9448a06fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("representative_name", sa.String(), nullable=False),
        sa.Column("representative_surname", sa.String(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("logo", sa.String(), nullable=False),
        sa.Column("inn", sa.String(), nullable=False),
        sa.Column("contact_number", sa.String(), nullable=False),
        sa.Column("contact_email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "universities_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("representative_name", sa.String(), nullable=False),
        sa.Column("representative_surname", sa.String(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("logo", sa.String(), nullable=False),
        sa.Column("inn", sa.String(), nullable=False),
        sa.Column("contact_number", sa.String(), nullable=False),
        sa.Column("contact_email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("universities_info")
    op.drop_table("companies_info")
    # ### end Alembic commands ###
